#!/bin/bash

dev=${1-/dev/input/event5}

event-parse () {
  printf '%08x%04x%04x%016x%016x' "$3" "$2" "$1" "$(date +%N)" "$(date +%s)"
}

event-queue () {
  # event-queue type code value
  buf+=`event-parse $*`
}

event-send () {
  echo "$buf"                             |\
    # UnHexify
    xxd -r -p                             |\
    # Convert to Little-Endian
    perl -0777e 'print scalar reverse <>' |\
    # Inject
    sudo tee "$dev" >/dev/null

  buf=
}

emulate-key () {
  event-queue 0 0    0       # EV_SYN SYN_REPORT
  event-queue 1 "$1" "$2"    # EV_KEY KEY/BTN UP/DOWN
  event-queue 4 4    0x90001 # EV_MSC MSC_SCAN
  event-send
}

emulate-keydown () {
  emulate-key "$1" 1
}

emulate-keyup () {
  emulate-key "$1" 0
}

emulate-keypress () {
  # sendkeypress keycode duration
  emulate-keydown "$1"
  sleep           "$2"
  emulate-keyup   "$1"
}

stdio-unbuffer () {
  script -q -c "$*" /dev/null
}

date-now () {
  date +%s%N | cut -c 1-13
}

random () {
  echo "$(($1 + ($RANDOM % ($2 - $1))))"
}

# constants
lmb=`event-parse 1 0x110 0 | cut -c 1-16`
clicks=()

stdio-unbuffer sudo od -vt x8 -w24 --endian=little "$dev" |\
while :; do
  test ! `cat $(dirname "$0")/state` && continue

  now=`date-now`
  read -n 24 -t 0 && {
    read -n 24 -d ' ' _ tv_sec tv_usec _
    ((skip--)) && continue || skip=0

    type=`cut -c 13-16 <<< "$_"`
    code=`cut -c 9-12 <<< "$_"`
    value=`cut -c 1-8 <<< "$_"`

    rg -q "\^$lmb\$" <<< "$value$code$type" && {
      S=()
      for k in "${!clicks[@]}"; do
        S+=($((now - clicks[k])))
        ((S[-1] > 1000)) && unset "clicks[$k]"
      done
      clicks=("$now" ${clicks[@]})

      ((${#S[@]} > 1)) && {
        ((n=0, m=0, p=0, B=1000 * S[-1] * S[-1]))
        for s in "${S[@]}"; do
          ((m += i = (B / (s * s)), \
            n += i * (s - p), \
            p = s))
        done

        ((d=`random 8 12` * n / (20 * m)))
        ((d < 369)) && (((d+=now) < delay || ! delay)) && delay=d
      }
    }
  }

  ((delay && delay < now)) && {
    ((delay=, skip++))
    emulate-keypress 0x110 0 # Left Mouse Button
  }
done
