#!/bin/bash

dev=${1-/dev/input/event5}

cwd=`dirname "$0"`

. "$cwd"/libs/util
. "$cwd"/libs/evdev

event-pack 1 0x110 0
event-parse
event-unpack
lmb=$value$code$type

stdio-unbuffer sudo xxd -p -c 24 "$dev" |\
while true; do
  test ! `cat "$cwd"/state` && continue

  now=`date-now`
  read -t 0 && {
    read event && event-unpack

    test "$value$code$type" = "$lmb" && {
      ((skip--)) && continue || ((skip=0))
    
      S=()
      for k in "${!clicks[@]}"; do
        S+=($((now - clicks[k])))
        ((S[-1] > 1000)) && unset "clicks[$k]"
      done
      clicks=("$now" ${clicks[@]})

      ((${#S[@]} > 1)) && {
        ((n=0, m=0, p=0, B=1000 * S[-1] * S[-1]))
        for s in "${S[@]}"; do
          ((m += i = (B / (s * s)), \
            n += i * (s - p), \
            p = s))
        done

        ((d=`random 8 12` * n / (20 * m)))
        ((d < 369)) && (((d+=now) < delay || ! delay)) && delay=d
      }
    }
  }

  ((delay && delay < now)) && {
    ((delay=0, skip++))
    emulate-keypress 0x110 0 # Left Mouse Button
  }
done
