#!/bin/bash

err () { echo $* >&2; }

hex-endian-swap () {
  h=$(printf "%0$((a=$1 + $1 % 2))x" "$(cat -)")

  for ((s = "${#h}"; (s-=2) >= 0;)); do
    printf "${h:s:2}"
  done
}

date-now () { date +%s%N | cut -c 1-13; }
timer-start () { timer=$(date-now); }
timer-stop () { err $(($(date-now) - timer)); }

random () { echo "$(($1 + ($RANDOM % ($2 - $1))))"; }

stdio-unbuffer () { SHELL=/bin/bash script -q -c "$*" /dev/null; }

